### ISSUE TITLE
Replace Accordion with tabs

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#13]
Remove the Accordion vertical structure and replace it with clickable tabs which show/hide the designated div.  

Selected/active tabs should have tab_active CSS class; inactive tabs should have tab_inactive CSS class.  Background graphics are already in the assets/images folder.

**Comment by derula** [comment]
Have a look at the original profile template to see what needs to be changed. Basically:

- Have a wrapping element with class "tabs"
- The first child of this element has to be a \<ul>
- All remaining children will be the contents of the individual tabs.

I could technically change the class name, too, but jQueryUI assigns them automatically, so it's easier to change them in the CSS. jQueryUI assigns the following classes (among some others):

- ui-tab, for all tabs
- ui-tabs-active, for all active tabs
- ui-state-active, for all active elements

Hope that's okay :)
