### ISSUE TITLE
Redo frame for 780x700 viewport

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#15]
Currently sized as 600x515.  Verified in-game browser window is 780x700.  Will require minor CSS changes and re-doing some background graphics.  (Note to self for after vacation.)

**Comment by derula** [comment]
Can you make it responsive? Like so its size changes with window size? Advantage would be that you could link to your character profile and allow people to open it in a real browser in order to be able to read it better.

**Comment by samera999** [comment]
I'm fairly certain I can set a width and height for the window if you'd prefer.
