### ISSUE TITLE
Change URL to include CharID

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#19]
Need to swap the backend (and front end) from front/Nick/First/Last to something like this:

https://profile.swlrp.com/front/12345?first=Chuck&nick=TexasRanger&last=Norris

**Comment by samera999** [comment]
Flash part is done, just needs the word that it's ready on the back end and I'll uncomment the code.

**Comment by derula** [comment]
@samera999, please note that #4 still needs to be done. basically this will mean that you'll have to replace front in @spellsmith's example with edit. I will provide you with examples in #4 once it's done.
