### ISSUE TITLE
Include Mod Version in URL for display on webpage

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#21]
It'd be useful to have the Mod version in the URL and somehow post that in the resulting webpage, so people can see at a glance, a literal glance, what version of the mod they are on.  

Example:
https://swlrp.incertitu.de/view/Sanneke

(The 'noprofile.php' template)

It displays a small "Beta 0.1" down at the bottom that is hardcoded into the template.  Rather than do this server side, though, we should do it clientside.  Or, we could do clientside and server side, to track / see different versions (i.e. someone has XYZ problem.  Their screen will tell them -- and thus us -- that they're on SWLRP Mod 1.4_s2.0   --  client mod 1.4, server side 2.0).

**Comment by samera999** [comment]
Easy enough to do on my end.  Have an additional parameter on the URL or stick something at the bottom for a version number.  Would have to add a text box field but that should be doable.  Or we can do what TSWRP mod did and have a tooltip on mouseover for the button.

**Comment by spellsmith** [comment]
[2:25 PM] derula: It might be better if the client just sends its version, and the backend has a list of versions that work, and if the client version isn't in the list, it'll show a warning and a link to update the mod
[2:27 PM] Spellsmith: That sounds like a very good solution
[2:27 PM] Spellsmith: more work for you >.>  but a good solution!
[2:27 PM] Samera: Agreed.  That way they'll know an update is available.
[2:28 PM] Samera: Or just forget the list and anytime there's an update with a version mismatch, put up a warning.

**Comment by samera999** [comment]
Let me know how you want me to add the version.  ?version=[Version] at the end?

**Comment by derula** [comment]
I'm thinking &clientVersion=[version]. However, in my view, this is low priority for now, and can be added after release. It's not a lot of work, but there are some things that definitely have to be addressed before release.

**Comment by derula** [comment]
Final parameter is clientVer.

**Comment by samera999** [comment]
So it's in the URL now.  I guess close this when it's on the webpage?

**Comment by derula** [comment]
Will do. (It isn't yet, I'll add it when there's some time)
