### ISSUE TITLE
Style <code> and <blockquote>

### ISSUE THREAD

**Issue by derula** [derula/swlrp-server#31]
SCEditor has options to insert code / quote.

Outside of the editor, this simply results in an unstyled \<code> / \<blockquote> tag.

Only default browser styles are applied: For code, it just changes the font. For blockquote, it just adds an indent.

It would be nice to apply special CSS to these two tags so that this feature has more of a point.

**Comment by spellsmith** [comment]
Added styling to blockquote and code both in the editor window and the normal view.

This required editing style.css and the SCEditor min.css, as I could not find a way to overwrite the SCEditor values even with very specific selectors.  I presume this is due to how SCEditor loads its CSS.

**Comment by spellsmith** [comment]
Completed styling; will commit the min.css with the branch so it can be pointed to for the SCE editor.
