### ISSUE TITLE
Changes to UI Dialog texts

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#33]
For 'Add/Change Portrait' function:  

Currently:

> Here, you can provide a URL for an image to be used as your character portrait.

Suggested: 

>Please enter the URL for your character portrait.  Size:  200x200.

--------------

For 'Change Password' function:

Currently:

> To change the password for ((NAME)), please provide your current password as well as the desired new password.

Suggested:

> Enter the fields below to change the password for ((NAME)).

**Comment by derula** [comment]
The character portrait can actually be any size, larger values will just be downsized. So maybe the text can reflect that. Maybe "target size" or "frame size"? Not a big deal, though. Other than that, I have no objections. The texts are basically placeholders anyway.

You can change the texts in editorDialogs.php (in case you didn't find that).

**Comment by spellsmith** [comment]
Altered editorDialogs.php to reflect desired changes and clarify size of portrait image.
