### ISSUE TITLE
Finalize link on "No Profile" page

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#36]
Right now the NoProfile.php template shows the following:

> /tell Some NPC (( Hey! If you're a roleplayer, have you seen the SWLRP mod? https://profile.swlrp.com ))

Before launch we will need to finalize this link to the proper mod download location.

My suggestion is either Curse or hosted off the SWLRP website itself.  Preferences?

**Comment by derula** [comment]
Like I said in the discord, my suggestion would be to leave the link as it is, and add a module to the server that will actually show the website with download link for it. Doing that will make it easier down the road to add more features to it, such as a profile listing etc, or maybe some fun statistics.

But if you don't like that, I'll just add an entry in config.yml to set the URL to something.

**Comment by spellsmith** [comment]
1) Description of mod
2) Download link
3) screenshots
4) Readme
5)  FAQ/Known Issues 
6) Steam install instructions
7) straight client instructions

(That I can think of right now, I'll put this in the comments)
