### ISSUE TITLE
Text editor in OOC tab is 1/2 width

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#46]
While the text-editor window appears to be full-width in the OOC screen, if you type something it word-wraps at about 50% width.

The problem is this:

.sceditor-container iframe, .sceditor-container textarea {
    width: 440px !important;
    height: 400px !important;
}

but I need to make sure the fix doesn't break the other tabs as well.

**Comment by derula** [comment]
Resolved by #47
