### ISSUE TITLE
Add universe differentiation

### ISSUE THREAD

**Issue by derula** [derula/swlrp-server#5]
This project was born mainly because its predecessor didn't have universe differentiation. We should be one step ahead and Implement it from the start.

**Comment by samera999** [comment]
What do you mean by universe differentiation?

**Comment by derula** [comment]
Like allow the same server to handle separate profiles for e.g. TSW and SWL without conflicting.

It's not really needed, but would be a nice-to-have.

**Comment by derula** [comment]
Closing because not needed at the moment.
